// dotenv removed
const mongoose = require('mongoose');
const MenuItem = require('./models/MenuItem'); // Ensure this path is correct

const items = [
  {
    name: "Classic Veg Burger",
    category: "Fast Food",
    station: "Fast Food",
    price: 80,
    basePrice: 80,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200000/canteen/classic-veg-burger.jpg",
    description: "A hearty veggie patty with fresh lettuce, tomatoes, and home-made sauce in a toasted bun.",
    availability: true,
    isVeg: true,
    preparationTime: 10,
    stockQuantity: 50,
    tags: ["burger", "veg", "popular", "fast-food"],
    canteen: null,
    avgRating: 4.5,
    ratingCount: 120
  },
  {
    name: "Chicken Zinger Burger",
    category: "Fast Food",
    station: "Fast Food",
    price: 120,
    basePrice: 120,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200001/canteen/chicken-zinger.jpg",
    description: "Crispy fried chicken breast with spicy mayo and fresh lettuce in a sesame bun.",
    availability: true,
    isVeg: false,
    preparationTime: 15,
    stockQuantity: 40,
    tags: ["burger", "non-veg", "spicy", "chicken"],
    canteen: null,
    avgRating: 4.8,
    ratingCount: 200
  },
  {
    name: "Margherita Pizza",
    category: "Fast Food",
    station: "Fast Food",
    price: 150,
    basePrice: 150,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200002/canteen/margherita-pizza.jpg",
    description: "Classic pizza with rich tomato sauce, fresh mozzarella, and aromatic basil leaves.",
    availability: true,
    isVeg: true,
    preparationTime: 20,
    stockQuantity: 30,
    tags: ["pizza", "veg", "cheese", "italian"],
    canteen: null,
    avgRating: 4.6,
    ratingCount: 150
  },
  {
    name: "Pepperoni Pizza",
    category: "Fast Food",
    station: "Fast Food",
    price: 180,
    basePrice: 180,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200003/canteen/pepperoni-pizza.jpg",
    description: "Delicious pizza topped with spicy pepperoni slices and melted cheese.",
    availability: true,
    isVeg: false,
    preparationTime: 20,
    stockQuantity: 25,
    tags: ["pizza", "non-veg", "spicy", "meat"],
    canteen: null,
    avgRating: 4.7,
    ratingCount: 180
  },
  {
    name: "Masala Dosa",
    category: "Meals",
    station: "Main Course",
    price: 60,
    basePrice: 60,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200004/canteen/masala-dosa.jpg",
    description: "Crispy rice crepe stuffed with spiced potato filling, served with sambar and chutney.",
    availability: true,
    isVeg: true,
    preparationTime: 15,
    stockQuantity: 100,
    tags: ["south-indian", "veg", "breakfast", "dosa"],
    canteen: null,
    avgRating: 4.9,
    ratingCount: 300
  },
  {
    name: "Paneer Butter Masala Meal",
    category: "Meals",
    station: "Main Course",
    price: 140,
    basePrice: 140,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200005/canteen/paneer-butter-masala.jpg",
    description: "Rich and creamy paneer curry served with 2 butter naan and rice.",
    availability: true,
    isVeg: true,
    preparationTime: 25,
    stockQuantity: 40,
    tags: ["north-indian", "veg", "lunch", "paneer"],
    canteen: null,
    avgRating: 4.7,
    ratingCount: 220
  },
  {
    name: "Chicken Biryani",
    category: "Meals",
    station: "Main Course",
    price: 160,
    basePrice: 160,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200006/canteen/chicken-biryani.jpg",
    description: "Aromatic basmati rice cooked with tender chicken pieces and secret spices. Served with raita.",
    availability: true,
    isVeg: false,
    preparationTime: 30,
    stockQuantity: 50,
    tags: ["biryani", "non-veg", "lunch", "popular"],
    canteen: null,
    avgRating: 4.9,
    ratingCount: 400
  },
  {
    name: "Veg Hakka Noodles",
    category: "Fast Food",
    station: "Fast Food",
    price: 90,
    basePrice: 90,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200007/canteen/veg-hakka-noodles.jpg",
    description: "Stir-fried noodles with fresh vegetables and soya sauce.",
    availability: true,
    isVeg: true,
    preparationTime: 12,
    stockQuantity: 60,
    tags: ["chinese", "veg", "noodles", "spicy"],
    canteen: null,
    avgRating: 4.4,
    ratingCount: 140
  },
  {
    name: "Cold Coffee",
    category: "Beverages",
    station: "Beverages",
    price: 50,
    basePrice: 50,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200008/canteen/cold-coffee.jpg",
    description: "Chilled, creamy and thick cold coffee made with rich espresso.",
    availability: true,
    isVeg: true,
    preparationTime: 5,
    stockQuantity: 200,
    tags: ["drink", "coffee", "cold", "sweet"],
    canteen: null,
    avgRating: 4.8,
    ratingCount: 350
  },
  {
    name: "Fresh Lime Soda",
    category: "Beverages",
    station: "Beverages",
    price: 40,
    basePrice: 40,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200009/canteen/fresh-lime-soda.jpg",
    description: "Refreshing sweet and salty lime soda.",
    availability: true,
    isVeg: true,
    preparationTime: 5,
    stockQuantity: 150,
    tags: ["drink", "refreshing", "cold", "soda"],
    canteen: null,
    avgRating: 4.5,
    ratingCount: 180
  },
  {
    name: "Chocolate Brownie",
    category: "Desserts",
    station: "Desserts",
    price: 70,
    basePrice: 70,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200010/canteen/chocolate-brownie.jpg",
    description: "Fudgy and gooey chocolate brownie topped with chocolate syrup.",
    availability: true,
    isVeg: true,
    preparationTime: 5,
    stockQuantity: 80,
    tags: ["dessert", "sweet", "chocolate", "baked"],
    canteen: null,
    avgRating: 4.7,
    ratingCount: 210
  },
  {
    name: "Gulab Jamun (2 pcs)",
    category: "Desserts",
    station: "Desserts",
    price: 40,
    basePrice: 40,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200011/canteen/gulab-jamun.jpg",
    description: "Soft and spongy milk solids soaked in warm cardamom infused sugar syrup.",
    availability: true,
    isVeg: true,
    preparationTime: 2,
    stockQuantity: 100,
    tags: ["dessert", "sweet", "indian", "traditional"],
    canteen: null,
    avgRating: 4.6,
    ratingCount: 160
  },
  {
    name: "Grilled Sandwich",
    category: "Snacks",
    station: "Grill",
    price: 60,
    basePrice: 60,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200012/canteen/grilled-sandwich.jpg",
    description: "Crispy grilled sandwich loaded with veggies, cheese, and green chutney.",
    availability: true,
    isVeg: true,
    preparationTime: 8,
    stockQuantity: 70,
    tags: ["sandwich", "veg", "snack", "cheese"],
    canteen: null,
    avgRating: 4.3,
    ratingCount: 130
  },
  {
    name: "French Fries",
    category: "Snacks",
    station: "Fast Food",
    price: 50,
    basePrice: 50,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200013/canteen/french-fries.jpg",
    description: "Crispy golden french fries served with tomato ketchup.",
    availability: true,
    isVeg: true,
    preparationTime: 10,
    stockQuantity: 120,
    tags: ["snack", "potato", "fried", "veg"],
    canteen: null,
    avgRating: 4.5,
    ratingCount: 250
  },
  {
    name: "Samosa (2 pcs)",
    category: "Snacks",
    station: "General",
    price: 30,
    basePrice: 30,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200014/canteen/samosa.jpg",
    description: "Crispy pastry filled with spicy mashed potato and peas.",
    availability: true,
    isVeg: true,
    preparationTime: 5,
    stockQuantity: 150,
    tags: ["snack", "indian", "spicy", "potato"],
    canteen: null,
    avgRating: 4.8,
    ratingCount: 300
  },
  {
    name: "Egg Fried Rice",
    category: "Meals",
    station: "Main Course",
    price: 100,
    basePrice: 100,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200015/canteen/egg-fried-rice.jpg",
    description: "Classic Chinese style fried rice with scrambled eggs and veggies.",
    availability: true,
    isVeg: false,
    preparationTime: 15,
    stockQuantity: 60,
    tags: ["chinese", "rice", "egg", "non-veg"],
    canteen: null,
    avgRating: 4.4,
    ratingCount: 110
  },
  {
    name: "Mango Smoothie",
    category: "Beverages",
    station: "Beverages",
    price: 70,
    basePrice: 70,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200016/canteen/mango-smoothie.jpg",
    description: "Thick and creamy mango smoothie made with fresh mangoes and yogurt.",
    availability: true,
    isVeg: true,
    preparationTime: 5,
    stockQuantity: 50,
    tags: ["drink", "smoothie", "mango", "sweet"],
    canteen: null,
    avgRating: 4.7,
    ratingCount: 190
  },
  {
    name: "Veg Roll",
    category: "Snacks",
    station: "Grill",
    price: 50,
    basePrice: 50,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200017/canteen/veg-roll.jpg",
    description: "Spicy mixed vegetable filling wrapped in a soft paratha.",
    availability: true,
    isVeg: true,
    preparationTime: 10,
    stockQuantity: 80,
    tags: ["roll", "snack", "veg", "spicy"],
    canteen: null,
    avgRating: 4.2,
    ratingCount: 90
  },
  {
    name: "Chicken Roll",
    category: "Snacks",
    station: "Grill",
    price: 80,
    basePrice: 80,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200018/canteen/chicken-roll.jpg",
    description: "Succulent chicken chunks marinated in spices, wrapped in a flaky paratha.",
    availability: true,
    isVeg: false,
    preparationTime: 12,
    stockQuantity: 70,
    tags: ["roll", "snack", "non-veg", "chicken"],
    canteen: null,
    avgRating: 4.6,
    ratingCount: 150
  },
  {
    name: "Idli Sambar (3 pcs)",
    category: "Meals",
    station: "General",
    price: 40,
    basePrice: 40,
    image: "https://res.cloudinary.com/dyqfrowxw/image/upload/v1710200019/canteen/idli-sambar.jpg",
    description: "Soft and fluffy steamed rice cakes served with hot lentil soup and chutney.",
    availability: true,
    isVeg: true,
    preparationTime: 5,
    stockQuantity: 100,
    tags: ["south-indian", "veg", "breakfast", "healthy"],
    canteen: null,
    avgRating: 4.5,
    ratingCount: 170
  }
];

const runSeed = async () => {
  try {
    await mongoose.connect('mongodb+srv://vsrr2006_db_user:vishnu123@openly.y3iowlc.mongodb.net/');
    console.log('MongoDB connected.');
    
    await MenuItem.deleteMany({});
    console.log('Cleared existing menu items.');

    const result = await MenuItem.insertMany(items);
    console.log(`Successfully added ${result.length} items to database`);
  } catch (error) {
    console.error('Error seeding items:');
    console.error(error);
  } finally {
    mongoose.connection.close();
  }
};

runSeed();
